#!/bin/bash

# Pre commit hook that prevents FORBIDDEN code from being commited.
# Add unwanted code to the FORBIDDEN array as necessary

FORBIDDEN=( TODO FIXME )

for i in "${FORBIDDEN[@]}"
do
    git diff -p -M --cached HEAD -- | grep '^+' | grep $i && \
        echo 'COMMIT REJECTED Found'  $i 'references. Please remove them before commiting.' && exit 1
done

exit 0
