#!/bin/sh
#
# Automatically adds branch name and branch description to every commit message.
#
FULL_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
BRANCH_NAME=$(echo $FULL_BRANCH_NAME | tr "[:lower:]" "[:upper:]" | sed 's/\([A-Z]\+-[0-9]\+\).*/\1/')

if [ "$FULL_BRANCH_NAME" = "HEAD" ]; then
    exit 0
fi
if [[ "$(cat $1)" =~ .*fixup.* ]]; then
    exit 0
fi
if [[ "$(cat $1)" =~ .*$BRANCH_NAME.* ]]; then
    exit 0
fi
if ! [ ${#BRANCH_NAME} -eq ${#FULL_BRANCH_NAME} ]; then
    echo "$(cat $1)\n\n$BRANCH_NAME" > $1
fi
